name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Running Test
      run: |
        echo starting test
        mkdir bin
        mkdir lib
        curl https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.5.2/junit-platform-console-standalone-1.5.2.jar -o lib/junit-platform-console-standalone-1.5.2.jar
        curl https://repo1.maven.org/maven2/org/jfree/jcommon/1.0.17/jcommon-1.0.17-javadoc.jar -o lib/jcommon.jar
        curl https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1-javadoc.jar -o lib/servlet.jar
        curl https://repo1.maven.org/maven2/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01-javadoc.jar -o lib/xml.jar
        javac -cp lib/jcommon.jar:lib/servlet.jar:lib/xml.jar:lib/ -d bin/ src/org/jfree/data/Range.java
        javac -d bin -cp bin:lib/junit-platform-console-standalone-1.5.2.jar test/*
        java -jar lib/junit-platform-console-standalone-1.5.2.jar --class-path bin --scan-class-path
